# Build a docker container suitable for splash development

FROM ubuntu:14.04
ENV DEBIAN_FRONTEND noninteractive

# Install, use dev tools, and then clean up in one RUN transaction
# to minimize image size.
ADD dockerfiles/splash/provision.sh /tmp/provision.sh

RUN /tmp/provision.sh \
    prepare_install \
    install_msfonts \
    install_builddeps \
    install_deps \
    install_extra_fonts \
    install_pyqt5 \
    install_python_deps \
    # remove_builddeps \
    # remove_extra \
    && \
    rm /tmp/provision.sh

RUN apt-get install --no-install-recommends -y libffi-dev libssl-dev
ADD requirements-dev.txt /tmp/requirements-dev.txt
RUN pip3 install -r /tmp/requirements-dev.txt && rm /tmp/requirements-dev.txt

ADD . /app
RUN pip3 install -e /app

VOLUME [ \
    "/etc/splash/proxy-profiles", \
    "/etc/splash/js-profiles", \
    "/etc/splash/filters", \
    "/etc/splash/lua_modules", \
    "/app" \
]

EXPOSE 8050 8051 5023

ENTRYPOINT "/bin/bash"
